### ISSUE TITLE
CDATA Issue

### ISSUE THREAD

**Issue by nosweat** [wankdanker/node-object-to-xml#1]
it escapes the cdata from <![CDATA[Text String]]> becomes &amp;lt;![CDATA[Text String]]&amp;gt;

Any idea how to make the object allow Cdata format?

```
{ MyCdata : {
                '@': {
                    'MyAttrId': AttrId
                },
                '#': "<![CDATA[Text String]]>"
            }};
```

**Comment by wankdanker** [comment]
I pushed v1.0.0 to npm with a check for CDATA strings that skips sanitizing.

It should allow you to do exactly what you specified in your example.

Let me know if you have any issues.

**Comment by nosweat** [comment]
@wankdanker thank you for quick response. I appreciate it. I tried the new version and it worked just fine.
